### ISSUE TITLE
 Wi-Fi does not work, pc restarts on login

### ISSUE THREAD

**Issue by gopinet** [xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh#11]
Hi, I use the same configuration of yours, except for the USB, I have the Z790 Aorus Elite AX Rev. 1.1 (nothing different with Rev. 1.0). When I started the installation it restarted when I wanted to activate the Wi-Fi, so I deactivated all the kext for Bluetooth and Wi-Fi. It let me install without any problem. After the installation, I tried to do the same and nothing, I still have the same problem.

I have Intel Wi-Fi 6E AX211. Thanks!!

**Comment by xtvj** [comment]
For Wi-Fi issues, you can manually download the latest kext file and replace the file in EFI. The link is: [https://github.com/OpenIntelWireless/itlwm/releases](https://github.com/OpenIntelWireless/itlwm/releases) 
The frequency of this Wi-Fi driver update is too fast, so I haven’t updated it to EFI in real time. Moreover, it can’t be guaranteed that it will definitely drive Wi-Fi, you can try it.

I often encounter the problem of the computer restarting when logging in. To be honest, I don’t know where the problem is and haven’t found a solution. Since updating Bios to F10, the probability of restarting has decreased a lot. If you can’t enter the system after restarting, you can execute ResetNram once and then enter the system.  netizens may have a solution.

**Comment by gopinet** [comment]
Thanks for your response, i log in and it restarts, it only happens to me with the internet, the Bluetooth works correctly. I put the latest Kext and nothing works.

**Comment by xtvj** [comment]
I am using the latest wifi driver, and after loading it, the Wifi successfully turns on and connects. 
My MacOS version: 14.4.1 
The driver I’m using: [AirportItlwm-Sonoma14.4-v2.3.0-DEBUG-alpha-e886ebb.zip](https://github.com/OpenIntelWireless/itlwm/releases/download/v2.3.0-alpha/AirportItlwm-Sonoma14.4-v2.3.0-DEBUG-alpha-e886ebb.zip)
 You can try it again.

**Comment by gopinet** [comment]
Thanks for your help, but with AirportItlwm kext it doesn't work for me, it restarts when I log in. At the moment I am using Itlwm with Heliport, everything is fine for the moment.
