### ISSUE TITLE
Intel Wifi Card Does it work

### ISSUE THREAD

**Issue by gkankanh** [xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh#2]
I know blue tooth works. Did the kext for intel AX211 Wifi card load and work? Just curious

**Comment by xtvj** [comment]
我加载了[itlwm-v2.2.0-DEBUG-alpha-5e30dc1.zip](https://github.com/OpenIntelWireless/itlwm/releases)，这个驱动是今天刚更新的，再安装[HeliPort](https://github.com/OpenIntelWireless/HeliPort/releases)，使用HeliPort软件扫描WIFI信息，目前可以扫描出WIFI列表，能连接WIFI，但电脑上不了网，可能需要开发者后续更新吧。

translate：
I loaded itlwm-v2.2.0-DEBUG-alpha-5e30dc1.zip, this kext was just updated today, and then installed HeliPort, using HeliPort software to scan WIFI information,
At present, the WIFI list can be scanned and connected, but the computer cannot access the Internet.
When The developer update it later, I will update EFI.

The same happens when using AirportItlwm.kext


<img width="1150" alt="截屏2023-05-13 22 35 27" src="https://github.com/xtvj/Gigabyte-Z790-Aorus-Elite-AX-13700K-OpenCore-Hackintosh/assets/11442821/9050dea7-7fa9-49a5-b232-0926ec99b65a">

**Comment by gkankanh** [comment]
Sounds very good. Thanks for the good work and responding. You can close this if you wish.
